### ISSUE TITLE
RGB camera as input instead of VR

### ISSUE THREAD

**Issue by Jason3900** [unitreerobotics/xr_teleoperate#55]
Thanks for your excellent work! I'm wondering is it possible to modify the code to take raw RGB camera stream as input(like anyteleop) instead of VR devices? Or which part should be edited to achieve this goal?

**Comment by silencht** [comment]
Hello. I'm not exactly sure what you mean. 
Currently, the image transmission data flow works as follows: 
`image_server.py` is responsible for capturing the image stream using either the V4L2 or RealSense driver, and then publishing it over a local network port using ZMQ.
The `image_client.py` subscribes to this image stream and transfers it via a shared memory mechanism to two destinations:   1. Display on the VR device;  2. Dataset recording. 

Could you please describe your question in more detail?

**Comment by Jason3900** [comment]
Thanks for reply. I mean that I don't want to rely on VR headset device to detect hand pose and etc.. I want to use RGB camera to replace it. But I don't know where to start. As far as I know, the VR headset is only responsible for two things, one is to detect human hand pose, the other is to get feedback from robot view. What I focus on is to detect a human's hand pose with only a 2D RGB camera followed by dex-retargeting or other lib and the feedback from robot view can be displayed in web browser.

**Comment by silencht** [comment]
You need to find an algorithm to obtain the wrist and finger pose information from 2D RGB image data. As far as I recall, anyteleop / dex-retargeting does not seem to have open-sourced the code for processing wrist poses (the dex-retargeting example uses MediaPipe to acquire finger skeletal keypoints pose). 

Once you have finalized the specific algorithm and obtained the raw wrist + finger pose data (It serves the same function as the [television.py](https://github.com/unitreerobotics/avp_teleoperate/blob/main/teleop/open_television/television.py)), you will need to transform the coordinate system of this data into the robot's reference frame (It serves the same function as the [tv_wrapper.py](https://github.com/unitreerobotics/avp_teleoperate/blob/main/teleop/open_television/tv_wrapper.py)).

website links you may be interested in: [mediapipe](https://github.com/google-ai-edge/mediapipe), [sapiens](https://github.com/facebookresearch/sapiens), [smpl](https://github.com/vchoutas/smplx), [humanoid teleoperate survey](https://arxiv.org/abs/2301.04317)

**Comment by Jason3900** [comment]
Thanks a lot! I'll try it!

**Comment by Jason3900** [comment]
@silencht Hey, I use a hand pose estimator which gives me the keypoints 21x3 hand keypoints and a rotation matrix. I use the keypoints[0] as wrist position, together with rotation matrix, I build a 4x4 matrix. While the rotation and movement of the wrist looks fine, the finger movement is tiny and scale up/down the number in the keypoints doesn't help much. Can you give me some clues?

**Comment by silencht** [comment]
The XR device provides a 25-point hand keypoint model, whereas hand pose estimators like MediaPipe use a 21-point model. The dex-retargeting library performs retargeting purely based on the input position data.

If you're using a 21-point hand pose estimator, refer to the original dex-retargeting examples — they use the MediaPipe library as input.

The necessary adjustments are usually made in the YAML configuration file(e.g. [dex3.yaml](https://github.com/unitreerobotics/xr_teleoperate/blob/main/assets/unitree_hand/unitree_dex3.yml)).

**reference image**
| OpenXR | MediaPipe |
|--------|-----------|
| <img src="https://github.com/user-attachments/assets/1055ecf8-4255-4f90-965d-cdbf3a9b6405" width="200"/> | <img src="https://github.com/user-attachments/assets/b403a2a0-4b0f-401d-80bb-0ad9617ecbc2" width="800"/> |

**Comment by Jason3900** [comment]
Thanks. I noticed that in the original Open-TeleVision. They only use finger tips for retargeting, right?
```python
left_qpos = self.left_retargeting.retarget(left_hand_mat[tip_indices])[[4, 5, 6, 7, 10, 11, 8, 9, 0, 1, 2, 3]]
```
In that case, using XR device as input, I can teleoperate it smoothly. But if I replace the XR device's data input to a hand pose estimator's predicted output, the teleoperate performance of fingers is bad (in both original TeleVision and avp_teleoperate). Is there something I should check?

**Comment by silencht** [comment]
The dex-retargeting library uses the positions of the wrist origin and fingertips to perform retargeting.
For example, in the five-finger hand's vector-based algorithm, the index mapping in the YAML file is shown as follows:
```yaml
  # for vector type
  target_origin_link_names: [ "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link"]
  target_task_link_names: [ "L_thumb_tip", "L_index_tip", "L_middle_tip", "L_ring_tip", "L_pinky_tip" ]
  target_link_human_indices_vector: [ [ 0, 0, 0, 0, 0 ], [ 4, 9, 14, 19, 24 ] ]
```
As you can see, the indices `4, 9, 14, 24, and 29` correspond to the five fingertips under the OpenXR standard. The link_names listed above also matches these index values.

If using a 21-point detector like MediaPipe, the values in the YAML file should be changed to:
```yaml
  target_origin_link_names: [ "base", "base", "base", "base", "base" ]
  target_task_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip" ]
  scaling_factor: 1.15

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [ [ 0, 0, 0, 0, 0 ], [ 4, 8, 12, 16, 20 ] ]
```
this code is come from [dex_retargeting/src/dex_retargeting/configs/teleop/inspire_hand_left.yml](https://github.com/dexsuite/dex-retargeting/blob/3f56141bc8bd2760d5e452e382937269554ebb21/src/dex_retargeting/configs/teleop/inspire_hand_left.yml#L8-L14)

As you can see, the indices `4, 8, 12, 16, and 20` are the five fingertip points in the MediaPipe hand detection results.

In addition, the coordinate system used in the URDF must align with the orientation of the input data from the hand pose detection. This issue is discussed in more detail in this issue https://github.com/dexsuite/dex-retargeting/issues/19.
